CREATE DATABASE QuanLyDaNgoai
DROP DATABASE QuanLyDaNgoai
USE QuanLyDaNgoai
SET DATEFORMAT DMY


CREATE TABLE HocSinh
(
	MaHS INT PRIMARY KEY IDENTITY,
	TenHS NVARCHAR(50),
	NgaySinh SMALLDATETIME,
	DiaChi NVARCHAR(50),
	TenCha NVARCHAR(50),
	TenMe NVARCHAR(50),
	TenNguoiDamHo NVARCHAR(50),
	SDT NVARCHAR(11),
)
CREATE TABLE NamHoc(
	MaNH INT PRIMARY KEY,
	TenNH NVARCHAR(20)
)
CREATE TABLE LopHoc
(

	MaLop NVARCHAR(6) PRIMARY KEY,
	TenLop NVARCHAR(20),
	MaNH INT FOREIGN KEY REFERENCES dbo.NamHoc(MaNH)
)


CREATE TABLE CTLop
(
	MaHS INT FOREIGN KEY REFERENCES dbo.HocSinh(MaHS),
	MaLop NVARCHAR(6) FOREIGN KEY REFERENCES dbo.LopHoc(MaLop), 
	CONSTRAINT pk_CTLop PRIMARY KEY(MaHS,MaLop)
)

CREATE TABLE GiaoVien(
	MaGV INT PRIMARY KEY IDENTITY,
	TenGV NVARCHAR(50),
	NgaySinh SMALLDATETIME,
	DiaChi NVARCHAR(50),
	SDT NVARCHAR(11),
	CMND NVARCHAR(12),
	MaLop NVARCHAR(6) FOREIGN KEY REFERENCES dbo.LopHoc(MaLop)
)


CREATE TABLE CongTyDuLich(
	MaCongTy INT PRIMARY KEY IDENTITY,
	TenCongTy NVARCHAR(50) NOT NULL,
	DiaChi NVARCHAR(50),
	SDT NVARCHAR(11)
)

CREATE TABLE DiaDiem
(
-- dia diem 
	MaDiaDiem INT PRIMARY KEY IDENTITY,
	TenDiaDiem NVARCHAR(50),
	DiaChi NVARCHAR(50),
)

CREATE TABLE ChuyenDi
(
	MaChuyenDi  INT PRIMARY KEY IDENTITY,
	MaCongTyDuLich INT FOREIGN KEY REFERENCES dbo.CongTyDuLich(MaCongTy),
	MaDiaDiem INT FOREIGN KEY REFERENCES dbo.DiaDiem(MaDiaDiem),
	GioKhoiHanh TIME,
	GioKetThuc TIME,
)

CREATE TABLE ChiTietChuyenDi(
	MaChuyenDi INT FOREIGN KEY REFERENCES dbo.ChuyenDi(MaChuyenDi),
	ThoiGian time(5),
	HoatDong nvarchar(255),
	GhiChu nvarchar(255)
)


CREATE TABLE ChiPhi
(
	MaDiaDiem INT FOREIGN KEY REFERENCES dbo.DiaDiem(MaDiaDiem),
	MaChuyenDi INT FOREIGN KEY REFERENCES dbo.ChuyenDi(MaChuyenDi),
	VeCong FLOAT,
	TienXe FLOAT,
	TienAnTrua FLOAT,
	PhiHuongDanVien FLOAT,
	NuocUong FLOAT,
	TienAnXe FLOAT,
	LinhTinh float,
	GhiChu NVARCHAR(255)
	CONSTRAINT pk_ChiPhi PRIMARY KEY (MaDiaDiem,MaChuyenDi)
)

CREATE TABLE HopDong
(
	MaHopDong INT PRIMARY KEY IDENTITY,
	MaChuyenDi INT FOREIGN KEY REFERENCES dbo.ChuyenDi(MaChuyenDi),
	MaCongTy INT FOREIGN KEY REFERENCES dbo.CongTyDuLich(MaCongTy),
	TriGia FLOAT
)
CREATE TABLE ThongTinThanhToan -- chi tiet hop dong
(
	MaHopDong INT FOREIGN KEY REFERENCES dbo.HopDong(MaHopDong),
	LanThanhToan INT,
	NgayThanhToan SMALLDATETIME,
	CONSTRAINT pk_ThongTinThanhToan PRIMARY KEY (MaHopDong,LanThanhToan)
)

CREATE TABLE HocSinhThamGia
(
	MaHS INT FOREIGN KEY REFERENCES dbo.HocSinh(MaHS),
	MaLop NVARCHAR(6) FOREIGN KEY REFERENCES dbo.LopHoc(MaLop),
	MaChuyenDi INT,
	ThamGia BIT,
	IsDongTien BIT,
	CONSTRAINT pk_HocSinhThamGia PRIMARY KEY (MaHS, MaLop, MaChuyenDi)
)

CREATE TABLE GiaoVienThamGia
(
	MaGiaoVien INT FOREIGN KEY REFERENCES dbo.GiaoVien(MaGV),
	MaLop NVARCHAR(6) FOREIGN KEY REFERENCES dbo.LopHoc(MaLop),
	MaChuyenDi INT,
	ThamGia BIT,
	CONSTRAINT pk_GiaoVienThamGia PRIMARY KEY (MaGiaoVien, MaLop, MaChuyenDi)
)

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[User](
	[ID] [int] NOT NULL,
	[Email] [nvarchar](50) NULL,
	[Password] [nvarchar](50) NULL,
	[Level] [int] NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]